version: '3'
name: micro-simple

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    environment:
      - MSSQL_SA_PASSWORD=Micro123
      - ACCEPT_EULA=1
    ports:
      - '1433:1433'
    networks:
      - micro-simple

  rabbitmq:
    image: rabbitmq:3.9.13-management
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro-simple

networks:
  micro-simple:
    name: micro-simple
